# Generated by Django 5.2.6 on 2025-10-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_medicamento_alter_perfil_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
