# Generated by Django 5.2.6 on 2025-12-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_especialidade_alter_consulta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('medico', 'Médico'), ('atendente', 'Atendente'), ('paciente', 'Paciente')], default='paciente', max_length=10),
        ),
    ]
