# Generated by Django 5.2.6 on 2025-12-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_alter_perfil_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('intervalo_minutos', models.PositiveIntegerField(default=30, help_text='Duração de cada consulta em minutos')),
                ('ativo', models.BooleanField(default=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='pessoas.profissional')),
            ],
            options={
                'verbose_name': 'Horário de Trabalho',
                'verbose_name_plural': 'Horários de Trabalho',
                'ordering': ['profissional', 'dia_semana', 'hora_inicio'],
                'unique_together': {('profissional', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
