# Generated by Django 5.2.6 on 2025-10-06 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_consulta_perfil_delete_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome comercial do medicamento.', max_length=200, unique=True)),
                ('foto', models.ImageField(blank=True, help_text='Foto da embalagem do medicamento.', null=True, upload_to='medicamentos/')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Preço do medicamento em R$.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('necessita_receita', models.BooleanField(default=True, help_text='Marque esta opção se o medicamento exige receita médica.')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('medico', 'Médico'), ('paciente', 'Paciente'), ('atendente', 'Atendente')], max_length=10),
        ),
    ]
